# Generated by Django 5.2.1 on 2025-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0017_clinical_examination_surgery_id_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_examination',
            name='surgery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
